### ISSUE TITLE
Unable to connect to the server

### ISSUE THREAD

**Issue by Nayana-Nagaraj** [actions-hub/kubectl#17]
Hello Team,

When we are trying to deploy  to Kubernetes which is hosted in our on prem server using your action template below is the errroe we are encountering: -
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

Can you please help us with the resolution

**Comment by exelban** [comment]
Sorry, but I have no idea why it does not work for you.

**Comment by Henchway** [comment]
Were you ever able to resolve this?
