### ISSUE TITLE
Why cant this action use the aws cli?

### ISSUE THREAD

**Issue by OzyOzk** [actions-hub/kubectl#18]
I'm setting up my AWS credentials with aws-actions/configure-aws-credentials@v1 and using the  aws-actions/amazon-ecr-login@v1 to log into AWS ECR and yet when I use the kubectl action it cant find aws-cli that was used in the previous step.

**Comment by exelban** [comment]
because there is no `aws cli` in this image. It's a tiny image that contains the `kubectl`. And nothing more.
