### ISSUE TITLE
cluster-info

### ISSUE THREAD

**Issue by logikaljay** [actions-hub/kubectl#21]
running `CMD "cluster-info"` in the Dockerfile prevents users from using a namespace scoped service account without access to list `services` in `kube-system`.

```
Error from server (Forbidden): services is forbidden: User "system:serviceaccount:my-app:github-ci" cannot list resource "services" in API group "" in the namespace "kube-system"
```

Is there a reason `cluster-info` is run? or it is just to log info in the github action logs?

**Comment by exelban** [comment]
yes, you have the wrong token. Read the error.
