### ISSUE TITLE
Always throws an error "It looks like you are trying to use a client-go credential plugin that is not installed."

### ISSUE THREAD

**Issue by partounian** [actions-hub/kubectl#25]
```
It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

The error doesn't occur when I use the same kubeconfig secret with `azure/setup-kubectl@v3` and `azure/k8s-set-context@v3`

**Comment by noaKurman** [comment]
Hey @partounian! We're having the same issue, Do you have a workaround for that?

**Comment by partounian** [comment]
Try @noaKurman base64 encoding the kubeconfig if you haven't. If you have encoded it then try not encoding it.

I ended up using  `azure/setup-kubectl@v3` & `azure/k8s-set-context@v3`.
