### ISSUE TITLE
"aws": executable file not found in $PATH

### ISSUE THREAD

**Issue by kayue** [actions-hub/kubectl#3]
Got the following 2 errors

```
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Unable to connect to the server: getting credentials: exec: exec: "aws": executable file not found in $PATH
```

I use the following commands to create kubeconfig file in Github Actions, not sure does it breaks anything

```
    - name: Create kubeconfig
      run: aws eks --region us-west-2 update-kubeconfig --name production-v1

    - name: Setting KUBE_CONFIG environment variable
      run: echo "KUBE_CONFIG=$(cat $HOME/.kube/config | base64 --wrap=0)" >> $GITHUB_ENV
```

**Comment by exelban** [comment]
Hi.

Thanks for reporting.
Github Action deprecates some command. I already fix it and now it must works.

**Comment by ghanshyam-onesliq** [comment]
Hi 
Unable to connect to the server: getting credentials: exec: exec: "aws": executable file not found in $PATH
I am still getting this error while trying to restart eks cluster.

**Comment by swananddhole** [comment]
I'm facing the same issue as @ghanshyam-onesliq, can anyone help me out here- 
![image](https://user-images.githubusercontent.com/94829261/201928817-be8d0f9a-199e-4761-8869-fcd1e11481ca.png)
