### ISSUE TITLE
k8s in self-hosted github runner - tcp 127.0.0.1:6443: connection refused

### ISSUE THREAD

**Issue by Dan1aR** [actions-hub/kubectl#30]
Hey everyone!
I was following the tutorial about self-hosted github runner for applying kubectl command and ran into this issue:

E1208 23:53:20.163003       7 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused

I provided base64 encoded .kube/config via secrets

github runner is hosted on the kubernetes control-plane (master) node, kubectl commands are working fine, when i run them from my ssh-terminal at that node, but when github runner does it into docker container, this issue occurs

Could someone please help me out on this?

**Comment by Dan1aR** [comment]
Moreover, if i clone repo, locally build image and execute it via docker with the same KUBE_CONFIG - everything works fine:

```
docker run \
    --workdir /github/workspace \
    -e "KUBE_CONFIG" \
    -v "/var/run/docker.sock":"/var/run/docker.sock" \
    -v "/home/dan1ar/actions-runner/_work/_temp/_github_home":"/github/home" \
    -v "/home/dan1ar/actions-runner/_work/_temp/_github_workflow":"/github/workflow" \
    -v "/home/dan1ar/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" \
    -v "/home/dan1ar/actions-runner/_work/arbitrage-unit/arbitrage-unit":"/github/workspace" \
    kubectl:latest get pod
```
Output contains all pods

**Comment by Dan1aR** [comment]
Ok, that is weird, if my self-hosted runner is on control-plane node - i face this error
Once i move runner to another node (worker) - it magically starts working
Any one knows, why?)

**Comment by alexlatif** [comment]
this is very strange as i am trying to do the same except not a self hosted runner.

i am getting a very similar

```yaml
      - name: Apply values to Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deployment.yaml
```

```
 failed to download openapi: Get "https://172.31.39.149:8443/openapi/v2?timeout=32s": dial tcp 172.31.39.149:8443: i/o timeout
 ```
 
i assume that your specific issue may be relating to it trying to potentially dial itself, and i believe mine has to do with not being able to externally access this tcp.

the other way approach i cannot seem to find anything related to a USERNAME_PASSWORD or TOKEN in my  ~/.kube/config

          # KUBE_HOST: ${{ secrets.KUBE_HOST }}
          # KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
          # KUBE_USERNAME: ${{ secrets.KUBE_USERNAME }}
          # KUBE_PASSWORD: ${{ secrets.KUBE_PASSWORD }}
