### ISSUE TITLE
v1.31.1 and master has error of /usr/local/bin/kubectl: line 1: syntax error: unexpected redirection

### ISSUE THREAD

**Issue by JinIgarashi** [actions-hub/kubectl#38]
I used `actions-hub/kubectl@master` in our GitHub action, and it suddenly gives me an error of `/usr/local/bin/kubectl: line 1: syntax error: unexpected redirection`.

when I specified the version v`1.31.0` in our CI, it works without error. Looks like there is some bug in v1.31.1 and master branch.

Our github action result is https://github.com/UNDP-Data/geohub/actions/runs/10831578197/job/30053896834

![image](https://github.com/user-attachments/assets/fdb0180d-a30b-4a19-b5de-b0b41f7485fb)

**Comment by amilalizada** [comment]
I have this issue also

**Comment by DokiDoki1103** [comment]
我也遇到这个问题

**Comment by cristianrat** [comment]
same issue for me
edit: `uses: actions-hub/kubectl@v1.28.0` seems to work fine, so dowgraded to that for now

**Comment by Aduril** [comment]
Was about to open the same issue 😂 
Thanks for the workaround @cristianrat !

Edit: I can verify that `uses: actions-hub/kubectl@v1.31.0` works as well for me

**Comment by nickkrykunov** [comment]
Same issue

**Comment by draveness** [comment]
same issue

**Comment by exelban** [comment]
Looks like v1.31.1 was withdrawn because right now google returns 1.31.0 as the latest release.
